configurations:
  number_of_job_profiles: 20
  vector_database_config:
    collection_name: "linkedin_job_profiles"
    database_type: "qdrant"
    index_path: "./qdrant_vector_store"
  embedding_model_config:
    gemini_embedding_model:
      model_id: "models/embedding-001"
      dimension: 768
    sentence_transformer_embedding_model:
      model_id: "sentence-transformers/all-MiniLM-L6-v2"
      dimension: 384
  llm_model_config:
    groq_model:
      model_id: "llama-3.3-70b-versatile"
      temperature: 0
    gemini_model:
      model_id: "gemini-2.0-flash"
      temperature: 0
  
